### PR TITLE
build and publish docker on release

### PR DESCRIPTION
**Pull request by delcroip**
Build the app within a container

add the action to publish the image on ghcr.io

Tested the image locally

### CODE REVIEW

**Comment by JPercival** [comment]
I'll also note that cqf-ruler is already built and published on release:

`docker run -p 8080:8080 cqframework/cqf-ruler:latest`

**Comment by delcroip** [comment]
I had the impression that the latest image was not aligned with the latest changes in github, that why I did that update

I will keep using it because I don't want my PC to be polluted by Java debs whenever I want to test the latest ruler code but feel free the close the PR.

Thanks for the reply and the link

FYI, regarding the Jar file it think you could also publish it on github package

**Comment by JPercival** [comment]
Yes, merges to `master` publish a new `latest` tag. `latest` is equivalent to `SNAPSHOT`. Stable releases get a tag following the ` vX.Y.Z.` pattern. Here's the most recent `SNAPSHOT` publish:

https://github.com/cqframework/cqf-ruler/actions/runs/4822049927/jobs/8588762214

**Comment by JPercival** [comment]
Closing given the discussion above. Maybe one day. :smiling_face_with_tear:

**Pull request closed without merging**
